name: Auto Reserve at Midnight

on:
  schedule:
    - cron: '0 15 * * *'  # JST 0:00（UTC 15:00）
  workflow_dispatch:

jobs:
  run-reservation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Chromeのダウンロードと展開
          wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # 既存のgoogle-chromeリンクを削除してから作成
          sudo rm -f /usr/bin/google-chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          # ChromeDriverのダウンロードと展開
          wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      - name: Run script
        run: python auto_reserve_tanaka.py
